---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: evepraisal
spec:
  selector:
    matchLabels:
      app: evepraisal
  replicas: 1
  template:
    metadata:
      labels:
        app: evepraisal
    spec:
      containers:
      - name: evepraisal
        image: sophaskins/evepraisal
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      - name: memcached
        image: memcached:latest
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: evepraisal
  name: evepraisal
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    name: http
  selector:
    app: evepraisal

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: evepraisal
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - evepraisal.burnitdown.biz
    secretName: evepraisal-tls
  rules:
  - host: evepraisal.burnitdown.biz
    http:
      paths:
      - path: /
        backend:
          serviceName: evepraisal
          servicePort: 80
